version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./migrations/_init.sql:/docker-entrypoint-initdb.d/init.sql
