

CREATE TABLE "employees" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL
);

CREATE TABLE "rooms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "opening_hours" timestamp NOT NULL,
  "closing_hourse" timestamp NOT NULL
);

CREATE TABLE "bookings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "start_time" timestamp NOT NULL,
  "end_time" timestamp NOT NULL,
  "employee_id" int,
  "room_id" int,
  "cancelled" boolean
);

ALTER TABLE "bookings" ADD FOREIGN KEY ("employee_id") REFERENCES "employees" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("room_id") REFERENCES "rooms" ("id");
