name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test

      - name: Check for failed tests
        run: |
          if [ $(grep -c "FAIL" ./test-report.txt) -ne 0 ]; then
            echo "Jest tests failed"
            exit 1
          fi